export * from './home/home.component';
export * from './about/about.component';
export * from './issuers/issuers.component';
export * from './payroll/payroll.component';
export * from './share-registration/share-registration.component';
export * from './shareholders/shareholders.component';
export * from './issuer-profile/issuer-profile.component';
export * from './news/news.component';
export * from './contacts/contacts.component';
